version: "3.8"

services:
  # This is the "Heart" - Your Spatial Database
  db:
    image: postgis/postgis:15-3.3
    container_name: opentrace_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: lemmaballs
      POSTGRES_DB: opentrace_map
    ports:
      - "5432:5432" # Maps your physical port 5432 to the container's 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # This saves your data even if you delete the container

  # This will be your Go Backend (We will build the Dockerfile for this later)
  # For now, it's just a placeholder to show you how they connect
  # api:
  #   build: ./backend
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"

volumes:
  postgres_data:
