version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: opentrace_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: lemmaballs
      POSTGRES_DB: opentrace_map
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
